name: Tests
on:
  pull_request:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    env:
      CGO_CFLAGS: -I/home/runner/go/deps/dqlite/include/
      CGO_LDFLAGS: -L/home/runner/go/deps/dqlite/.libs/
      LD_LIBRARY_PATH: /home/runner/go/deps/dqlite/.libs/
      CGO_LDFLAGS_ALLOW: (-Wl,-wrap,pthread_create)|(-Wl,-z,now)
    name: Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Require GHA pinning
        uses: canonical/lxd/.github/actions/require-gha-pinning@main

      - name: Dependency Review
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        if: github.event_name == 'pull_request'

      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'go.mod'

      - name: Check compatibility with min Go version
        run: |
          set -eux
          GOMIN="$(sed -n 's/^GOMIN=\([0-9.]\+\)$/\1/p' Makefile)"
          go mod tidy -go="${GOMIN}"

      - name: Install dependencies
        run: |
          set -eux
          sudo apt-get update

          sudo apt-get install --no-install-recommends -y \
            pkg-config autoconf automake libtool make libuv1-dev libsqlite3-dev liblz4-dev

      - name: Build dependencies
        run: |
          set -eux
          make deps

      - name: Run static analysis
        run: |
          set -eux
          make check-static

          make -C example check-static

      - name: Unit tests (all)
        run: |
          set -eux
          make check-unit

          make -C example check-unit

      - name: Example system tests
        run: |
          set -eux
          make -C example

          cd example/test
          CLUSTER_VERBOSE=1 ./main.sh
